name: Backup Base de Datos SQL

on:
  schedule:
    # Se ejecuta todos los días a las 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  backup:
    runs-on: windows-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar SqlPackage
        run: |
          choco install sqlpackage -y

      - name: Ejecutar Backup desde la Base de Datos
        env:
          # Aquí mapeamos TODOS los Secrets de GitHub a variables de entorno
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Construimos la cadena de conexión dinámicamente usando las variables de entorno
          $connString = "Server=tcp:$env:DB_HOST,$env:DB_PORT;Initial Catalog=$env:DB_NAME;User ID=$env:DB_USERNAME;Password=$env:DB_PASSWORD;Encrypt=True;TrustServerCertificate=False;"
          
          # Ejecutamos SqlPackage pasándole la cadena construida
          SqlPackage.exe /Action:Export /SourceConnectionString:"$connString" /TargetFile:"${{ github.workspace }}\backup.bacpac"

      - name: Subir archivo .bacpac como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: backup-bd
          path: ${{ github.workspace }}\backup.bacpac